//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicTier.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=udcsql2012;Initial Catalog=SD;User ID=sd;Password=kfe73fmf3F9f21dC;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;MultipleActiveResultSets=True.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\CSV\.
        /// </summary>
        internal static string CsvPath {
            get {
                return ResourceManager.GetString("CsvPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Datasets\.
        /// </summary>
        internal static string DataSetsPath {
            get {
                return ResourceManager.GetString("DataSetsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Errors\.
        /// </summary>
        internal static string ErrorPath {
            get {
                return ResourceManager.GetString("ErrorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string FutureDate {
            get {
                return ResourceManager.GetString("FutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDepartment20111201.
        /// </summary>
        internal static string GetDepartmentAction {
            get {
                return ResourceManager.GetString("GetDepartmentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEmployment20111201.
        /// </summary>
        internal static string GetEmploymentAction {
            get {
                return ResourceManager.GetString("GetEmploymentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEmploymentChanged20111201.
        /// </summary>
        internal static string GetEmploymentChangedAction {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEmploymentChangedAtDate20111201.
        /// </summary>
        internal static string GetEmploymentChangedAtDateAction {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAtDateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInstitution20111201.
        /// </summary>
        internal static string GetInstitutionAction {
            get {
                return ResourceManager.GetString("GetInstitutionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOrganization20111201.
        /// </summary>
        internal static string GetOrganizationAction {
            get {
                return ResourceManager.GetString("GetOrganizationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPerson20111201.
        /// </summary>
        internal static string GetPersonAction {
            get {
                return ResourceManager.GetString("GetPersonAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPersonChangedAtDate20111201.
        /// </summary>
        internal static string GetPersonChangedAtDateAction {
            get {
                return ResourceManager.GetString("GetPersonChangedAtDateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProfession20080201.
        /// </summary>
        internal static string GetProfessionAction {
            get {
                return ResourceManager.GetString("GetProfessionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Logs\.
        /// </summary>
        internal static string LogsPath {
            get {
                return ResourceManager.GetString("LogsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010-01-01.
        /// </summary>
        internal static string OldDate {
            get {
                return ResourceManager.GetString("OldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Resources\.
        /// </summary>
        internal static string ResourcesPath {
            get {
                return ResourceManager.GetString("ResourcesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up4ne43u.
        /// </summary>
        internal static string SDWSPassword {
            get {
                return ResourceManager.GetString("SDWSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sysyshb01.
        /// </summary>
        internal static string SDWSUsername {
            get {
                return ResourceManager.GetString("SDWSUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlfn37f433#F3f3d3cdevvw2d.
        /// </summary>
        internal static string UDCSDPassword {
            get {
                return ResourceManager.GetString("UDCSDPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service_udcsd.
        /// </summary>
        internal static string UDCSDUserame {
            get {
                return ResourceManager.GetString("UDCSDUserame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSCache.
        /// </summary>
        internal static string WebServiceCachePath {
            get {
                return ResourceManager.GetString("WebServiceCachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/.
        /// </summary>
        internal static string WebServiceUri {
            get {
                return ResourceManager.GetString("WebServiceUri", resourceCulture);
            }
        }
    }
}
