//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTier.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;ActivationTime&gt;00:00&lt;/ActivationTime&gt;.
        /// </summary>
        internal static string ActivationTime {
            get {
                return ResourceManager.GetString("ActivationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;AdministrationIndicator&gt;false&lt;/AdministrationIndicator&gt;.
        /// </summary>
        internal static string AdministrationIndicator {
            get {
                return ResourceManager.GetString("AdministrationIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=udcsql2012;Initial Catalog=SD_Test;User ID=sd;Password=kfe73fmf3F9f21dC;Connect Timeout=0;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;MultipleActiveResultSets=True.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;ContactInformationIndicator&gt;false&lt;/ContactInformationIndicator&gt;.
        /// </summary>
        internal static string ContactInformationIndicatorFalse {
            get {
                return ResourceManager.GetString("ContactInformationIndicatorFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;ContactInformationIndicator&gt;true&lt;/ContactInformationIndicator&gt;.
        /// </summary>
        internal static string ContactInformationIndicatorTrue {
            get {
                return ResourceManager.GetString("ContactInformationIndicatorTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\CSV\.
        /// </summary>
        internal static string CsvPath {
            get {
                return ResourceManager.GetString("CsvPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Datasets\.
        /// </summary>
        internal static string DataSetsPath {
            get {
                return ResourceManager.GetString("DataSetsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;DeactivationTime&gt;23:59&lt;/DeActivationTime&gt;.
        /// </summary>
        internal static string DeactivationTime {
            get {
                return ResourceManager.GetString("DeactivationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;DepartmentIdentifier&gt;&lt;/DepartmentIdentifier&gt;.
        /// </summary>
        internal static string DepartmentIdentifier {
            get {
                return ResourceManager.GetString("DepartmentIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;DepartmentIndicator&gt;true&lt;/DepartmentIndicator&gt;.
        /// </summary>
        internal static string DepartmentIndicator {
            get {
                return ResourceManager.GetString("DepartmentIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;DepartmentLevelIdentifier&gt;&lt;/DepartmentLevelIdentifier&gt;.
        /// </summary>
        internal static string DepartmentLevelIdentifier {
            get {
                return ResourceManager.GetString("DepartmentLevelIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;DepartmentNameIndicator&gt;true&lt;/DepartmentNameIndicator&gt;.
        /// </summary>
        internal static string DepartmentNameIndicator {
            get {
                return ResourceManager.GetString("DepartmentNameIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;DepartmentUUIDIdentifier&gt;&lt;/DepartmentUUIDIdentifier&gt;.
        /// </summary>
        internal static string DepartmentUUIDIdentifier {
            get {
                return ResourceManager.GetString("DepartmentUUIDIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;EffectiveDate&gt;.
        /// </summary>
        internal static string EffectiveDateBaseTag {
            get {
                return ResourceManager.GetString("EffectiveDateBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/EffectiveDate&gt;.
        /// </summary>
        internal static string EffectiveDateEndTag {
            get {
                return ResourceManager.GetString("EffectiveDateEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;EmploymentDepartmentIndicator&gt;true&lt;/EmploymentDepartmentIndicator&gt;.
        /// </summary>
        internal static string EmploymentDepartmentIndicator {
            get {
                return ResourceManager.GetString("EmploymentDepartmentIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;EmploymentIdentifier&gt;&lt;/EmploymentIdentifier&gt;.
        /// </summary>
        internal static string EmploymentIdentifier {
            get {
                return ResourceManager.GetString("EmploymentIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;EmploymentStatusIndicator&gt;true&lt;/EmploymentStatusIndicator&gt;.
        /// </summary>
        internal static string EmploymentStatusIndicator {
            get {
                return ResourceManager.GetString("EmploymentStatusIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Errors\.
        /// </summary>
        internal static string ErrorPath {
            get {
                return ResourceManager.GetString("ErrorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string FutureDate {
            get {
                return ResourceManager.GetString("FutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;FutureInformationIndicator&gt;true&lt;/FutureInformationIndicator&gt;.
        /// </summary>
        internal static string FutureInformationIndicator {
            get {
                return ResourceManager.GetString("FutureInformationIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetDepartment20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetDepartment20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetDepartment20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;DeactivationDate=9999-12-31&amp;ContactInformationIndicator=true&amp;DepartmentNameIndicator=true&amp;EmploymentDepartmentIndicator=true&amp;PostalAddressIndicator=true&amp;ProductionUnitIndicator=true&amp;UUIDIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetDepartment20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetDepartment20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetDepartment20111201.
        /// </summary>
        internal static string GetDepartmentActionUri {
            get {
                return ResourceManager.GetString("GetDepartmentActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetDepartment20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetDepartment/SD_GetDepartmentInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetDepartmentBaseTag {
            get {
                return ResourceManager.GetString("GetDepartmentBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetDepartment20111201&gt;.
        /// </summary>
        internal static string GetDepartmentEndTag {
            get {
                return ResourceManager.GetString("GetDepartmentEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetEmployment20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetEmployment20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetEmployment20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;StatusActiveIndicator=true&amp;StatusPassiveIndicator=true&amp;DepartmentIndicator=true&amp;EmploymentStatusIndicator=true&amp;ProfessionIndicator=true&amp;SalaryAgreementIndicator=true&amp;SalaryCodeGroupIndicator=true&amp;WorkingTimeIndicator=true&amp;UUIDIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetEmployment20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetEmployment20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetEmployment20111201.
        /// </summary>
        internal static string GetEmploymentActionUri {
            get {
                return ResourceManager.GetString("GetEmploymentActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetEmployment20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmployment/SD_GetEmploymentInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetEmploymentBaseTag {
            get {
                return ResourceManager.GetString("GetEmploymentBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetEmploymentChanged20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetEmploymentChanged20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetEmploymentChanged20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;DeactivationDate=9999-12-31&amp;DepartmentIndicator=true&amp;EmploymentStatusIndicator=true&amp;ProfessionIndicator=true&amp;SalaryAgreementIndicator=true&amp;SalaryCodeGroupIndicator=true&amp;WorkingTimeIndicator=true&amp;UUIDIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetEmploymentChanged20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetEmploymentChanged20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;sd:GetEmploymentChanged20111201 xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:sd=&quot;urn:oio:sd:snitflader:2011.12.01&quot; xsi:schemaLocation=&quot;urn:oio:sd:snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmploymentChanged/SD_GetEmploymentChangedInterface_20111201.xsd&quot; xmlns:cpr20050318=&quot;http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/&quot; xmlns:sd20070401=&quot;http://rep.oio.dk/sd.dk/xml.schema/20070401/&quot; xmlns:sd20080 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmploymentChanged20111201Replace {
            get {
                return ResourceManager.GetString("GetEmploymentChanged20111201Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetEmploymentChanged20111201.
        /// </summary>
        internal static string GetEmploymentChangedActionUri {
            get {
                return ResourceManager.GetString("GetEmploymentChangedActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetEmploymentChangedAtDate20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetEmploymentChangedAtDate20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAtDate20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;ActivationTime=00:00&amp;DeactivationDate=9999-12-31&amp;DeactivationTime=23:59&amp;DepartmentIndicator=true&amp;EmploymentStatusIndicator=true&amp;ProfessionIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetEmploymentChangedAtDate20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAtDate20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetEmploymentChangedAtDate20111201.
        /// </summary>
        internal static string GetEmploymentChangedAtDateActionUri {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAtDateActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetEmploymentChangedAtDate20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmploymentChangedAtDate/SD_GetEmploymentChangedAtDateInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetEmploymentChangedAtDateBaseTag {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAtDateBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetEmploymentChangedAtDate20111201&gt;.
        /// </summary>
        internal static string GetEmploymentChangedAtDateEndTag {
            get {
                return ResourceManager.GetString("GetEmploymentChangedAtDateEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetEmploymentChanged20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmploymentChanged/SD_GetEmploymentChangedInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetEmploymentChangedBaseTag {
            get {
                return ResourceManager.GetString("GetEmploymentChangedBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetEmploymentChanged20111201&gt;.
        /// </summary>
        internal static string GetEmploymentChangedEndTag {
            get {
                return ResourceManager.GetString("GetEmploymentChangedEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetEmployment20111201&gt;.
        /// </summary>
        internal static string GetEmploymentEndTag {
            get {
                return ResourceManager.GetString("GetEmploymentEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetInstitution20111201?RegionIdentifier=8P&amp;UUIDIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetInstitution20111201ActionUri {
            get {
                return ResourceManager.GetString("GetInstitution20111201ActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetInstitution20111201.
        /// </summary>
        internal static string GetInstitutionActionUri {
            get {
                return ResourceManager.GetString("GetInstitutionActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetInstitution20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetInstitution/SD_GetInstitutionInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetInstitutionBaseTag {
            get {
                return ResourceManager.GetString("GetInstitutionBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetInstitution20111201&gt;.
        /// </summary>
        internal static string GetInstitutionEndTag {
            get {
                return ResourceManager.GetString("GetInstitutionEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetOrganization20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetOrganization20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetOrganization20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;DeactivationDate=9999-12-31&amp;UUIDIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetOrganization20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetOrganization20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetOrganization20111201.
        /// </summary>
        internal static string GetOrganizationActionUri {
            get {
                return ResourceManager.GetString("GetOrganizationActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetOrganization20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetOrganization/SD_GetOrganizationInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetOrganizationBaseTag {
            get {
                return ResourceManager.GetString("GetOrganizationBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetOrganization20111201&gt;.
        /// </summary>
        internal static string GetOrganizationEndTag {
            get {
                return ResourceManager.GetString("GetOrganizationEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetPerson20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetPerson20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetPerson20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;StatusActiveIndicator=true&amp;StatusPassiveIndicator=true&amp;ContactInformationIndicator=true&amp;PostalAddressIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetPerson20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetPerson20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetPerson20111201.
        /// </summary>
        internal static string GetPersonActionUri {
            get {
                return ResourceManager.GetString("GetPersonActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetPersonChangedAtDate20111201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetPersonChangedAtDate20111201ActionUriBase {
            get {
                return ResourceManager.GetString("GetPersonChangedAtDate20111201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;ActivationTime=00:00&amp;DeactivationDate=9999-12-31&amp;DeactivationTime=23:59&amp;ContactInformationIndicator=true&amp;PostalAddressIndicator=true&amp;submit=OK.
        /// </summary>
        internal static string GetPersonChangedAtDate20111201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetPersonChangedAtDate20111201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetPersonChangedAtDate20111201.
        /// </summary>
        internal static string GetPersonChangedAtDateActionUri {
            get {
                return ResourceManager.GetString("GetPersonChangedAtDateActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetPersonChangedAtDate20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetPersonChangedAtDate/SD_GetPersonChangedAtDateInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetPersonChangedAtDateBaseTag {
            get {
                return ResourceManager.GetString("GetPersonChangedAtDateBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd.GetPersonChangedAtDate20111201&gt;.
        /// </summary>
        internal static string GetPersonChangedAtDateEndTag {
            get {
                return ResourceManager.GetString("GetPersonChangedAtDateEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetPerson20111201&gt;.
        /// </summary>
        internal static string GetPersonEndTag {
            get {
                return ResourceManager.GetString("GetPersonEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetPerson20111201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;urn:oio:sd:Snitflader:2011.12.01 https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetPerson/SD_GetPersonInterface_20111201.xsd&quot; &gt;.
        /// </summary>
        internal static string GetPersonTag {
            get {
                return ResourceManager.GetString("GetPersonTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetProfession20080201?InstitutionIdentifier=.
        /// </summary>
        internal static string GetProfession20080201ActionUriBase {
            get {
                return ResourceManager.GetString("GetProfession20080201ActionUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;submit=OK.
        /// </summary>
        internal static string GetProfession20080201ActionUriEnd {
            get {
                return ResourceManager.GetString("GetProfession20080201ActionUriEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/GetProfession20080201.
        /// </summary>
        internal static string GetProfessionActionUri {
            get {
                return ResourceManager.GetString("GetProfessionActionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:GetProfession20080201 xmlns:sd=&quot;urn:oio:sd:Snitflader:2011.12.01&quot; xsi:schemalocation=&quot;http://rep.oio.dk/sd.dk/xml.schema/20080201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20080201/SD_GetProfessionInterface.xsd&quot; &gt;.
        /// </summary>
        internal static string GetProfessionBaseTag {
            get {
                return ResourceManager.GetString("GetProfessionBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:GetProfession20080201&gt;.
        /// </summary>
        internal static string GetProfessionEndTag {
            get {
                return ResourceManager.GetString("GetProfessionEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;InstitutionIdentifier&gt;HB&lt;/InstitutionIdentifier&gt;.
        /// </summary>
        internal static string InstitutionIdentifier {
            get {
                return ResourceManager.GetString("InstitutionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;InstitutionIdentifier&gt;&lt;/InstitutionIdentifier&gt;.
        /// </summary>
        internal static string InstitutionIdentifierGetInstitution {
            get {
                return ResourceManager.GetString("InstitutionIdentifierGetInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;InstitutionUUIDIdentifier&gt;&lt;/InstitutionUUIDIdentifier&gt;.
        /// </summary>
        internal static string InstitutionUUIDIdentifier {
            get {
                return ResourceManager.GetString("InstitutionUUIDIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;JobPositionIdentifier&gt;&lt;/JobPositionIdentifier&gt;.
        /// </summary>
        internal static string JobPositionIdentifier {
            get {
                return ResourceManager.GetString("JobPositionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Logs\.
        /// </summary>
        internal static string LogsPath {
            get {
                return ResourceManager.GetString("LogsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010-01-01.
        /// </summary>
        internal static string OldDate {
            get {
                return ResourceManager.GetString("OldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;PersonCivilRegistrationIdentifier&gt;&lt;/PersonCivilRegistrationIdentifier&gt;.
        /// </summary>
        internal static string PersonCivilRegistrationIdentifier {
            get {
                return ResourceManager.GetString("PersonCivilRegistrationIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;PostalAddressIndicator&gt;true&lt;/PostalAddressIndicator&gt;.
        /// </summary>
        internal static string PostalAddressIndicatorFalse {
            get {
                return ResourceManager.GetString("PostalAddressIndicatorFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;PostalAddressIndicator&gt;true&lt;/PostalAddressIndicator&gt;.
        /// </summary>
        internal static string PostalAddressIndicatorTrue {
            get {
                return ResourceManager.GetString("PostalAddressIndicatorTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;ProductionUnitIndicator&gt;true&lt;/ProductionUnitIndicator&gt;.
        /// </summary>
        internal static string ProductionUnitIndicator {
            get {
                return ResourceManager.GetString("ProductionUnitIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;ProfessionIndicator&gt;true&lt;/ProfessionIndicator&gt;.
        /// </summary>
        internal static string ProfessionIndicator {
            get {
                return ResourceManager.GetString("ProfessionIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;RegionIdentifier&gt;8P&lt;/RegionIdentifier&gt;.
        /// </summary>
        internal static string RegionIdentifier {
            get {
                return ResourceManager.GetString("RegionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;RegionUUIDIdentifier&gt;&lt;/RegionUUIDIdentifier&gt;.
        /// </summary>
        internal static string RegionUUIDIdentifier {
            get {
                return ResourceManager.GetString("RegionUUIDIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;sd:RequestStructure&gt;.
        /// </summary>
        internal static string RequestStructureBaseTag {
            get {
                return ResourceManager.GetString("RequestStructureBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;/sd:RequestStructure&gt;.
        /// </summary>
        internal static string RequestStructureEndTag {
            get {
                return ResourceManager.GetString("RequestStructureEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Resources\.
        /// </summary>
        internal static string ResourcesPath {
            get {
                return ResourceManager.GetString("ResourcesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;SalaryAgreementIndicator&gt;true&lt;/SalaryAgreementIndicator&gt;.
        /// </summary>
        internal static string SalaryAgreementIndicator {
            get {
                return ResourceManager.GetString("SalaryAgreementIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;SalaryCodeGroupIndicator&gt;true&lt;/SalaryCodeGroupIndicator&gt;.
        /// </summary>
        internal static string SalaryCodeGroupIndicator {
            get {
                return ResourceManager.GetString("SalaryCodeGroupIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up4ne43u.
        /// </summary>
        internal static string SDWSPassword {
            get {
                return ResourceManager.GetString("SDWSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sysyshb01.
        /// </summary>
        internal static string SDWSUsername {
            get {
                return ResourceManager.GetString("SDWSUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;soapenv:Body&gt;.
        /// </summary>
        internal static string SoapBodyBaseTag {
            get {
                return ResourceManager.GetString("SoapBodyBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;/soapenv:Body&gt;.
        /// </summary>
        internal static string SoapBodyEndTag {
            get {
                return ResourceManager.GetString("SoapBodyEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;.
        /// </summary>
        internal static string SoapEnvelopeBaseTag {
            get {
                return ResourceManager.GetString("SoapEnvelopeBaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/soapenv:Envelope&gt;.
        /// </summary>
        internal static string SoapEnvelopeEndTag {
            get {
                return ResourceManager.GetString("SoapEnvelopeEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;StatusActiveIndicator&gt;true&lt;/StatusActiveIndicator&gt;.
        /// </summary>
        internal static string StatusActiveIndicator {
            get {
                return ResourceManager.GetString("StatusActiveIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;StatusPassiveIndicator&gt;true&lt;/StatusPassiveIndicator&gt;.
        /// </summary>
        internal static string StatusPassiveIndicator {
            get {
                return ResourceManager.GetString("StatusPassiveIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;UUIDIndicator&gt;true&lt;/UUIDIndicator&gt;.
        /// </summary>
        internal static string UUIDIndicatorLine {
            get {
                return ResourceManager.GetString("UUIDIndicatorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSCache.
        /// </summary>
        internal static string WebServiceCachePath {
            get {
                return ResourceManager.GetString("WebServiceCachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.sd.dk/sdws/.
        /// </summary>
        internal static string WebServiceURL {
            get {
                return ResourceManager.GetString("WebServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;WorkingTimeIndicator&gt;true&lt;/WorkingTimeIndicator&gt;.
        /// </summary>
        internal static string WorkingTimeIndicator {
            get {
                return ResourceManager.GetString("WorkingTimeIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:cpr20050318=&quot;http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/&quot; .
        /// </summary>
        internal static string XmlnsCpr {
            get {
                return ResourceManager.GetString("XmlnsCpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:cvr20050322=&quot;http://rep.oio.dk/cvr.dk/xml/schemas/2005/03/22/&quot; .
        /// </summary>
        internal static string XmlnsCvr {
            get {
                return ResourceManager.GetString("XmlnsCvr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:dkcc20050213=&quot;http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/&quot; xmlns:dkcc20050315=&quot;http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/&quot; .
        /// </summary>
        internal static string XmlnsDkcc {
            get {
                return ResourceManager.GetString("XmlnsDkcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:itst20050110=&quot;http://rep.oio.dk/itst.dk/xml/schemas/2005/01/10/&quot; xmlns:itst20050624=&quot;http://rep.oio.dk/itst.dk/xml/schemas/2005/06/24/&quot; .
        /// </summary>
        internal static string XmlnsItst {
            get {
                return ResourceManager.GetString("XmlnsItst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd20070301=&quot;http://rep.oio.dk/sd.dk/xml.schema/20070301/&quot; xmlns:sd20070401=&quot;http://rep.oio.dk/sd.dk/xml.schema/20070401/&quot; xmlns:sd20080201=&quot;http://rep.oio.dk/sd.dk/xml.schema/20080201/&quot; .
        /// </summary>
        internal static string XmlnsSd {
            get {
                return ResourceManager.GetString("XmlnsSd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetDepartment/SD_GetDepartmentInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetDepartment {
            get {
                return ResourceManager.GetString("XmlnsSdGetDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmployment/SD_GetEmploymentInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetEmployment {
            get {
                return ResourceManager.GetString("XmlnsSdGetEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmploymentChanged/SD_GetEmploymentChangedInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetEmploymentChanged {
            get {
                return ResourceManager.GetString("XmlnsSdGetEmploymentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetEmploymentChangedAtDate/SD_GetEmploymentChangedAtDateInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetEmploymentChangedAtDate {
            get {
                return ResourceManager.GetString("XmlnsSdGetEmploymentChangedAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetInstitution/SD_GetInstitutionInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetInstitution {
            get {
                return ResourceManager.GetString("XmlnsSdGetInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetOrganization/SD_GetOrganizationInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetOrganization {
            get {
                return ResourceManager.GetString("XmlnsSdGetOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetPerson/SD_GetPersonInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetPerson {
            get {
                return ResourceManager.GetString("XmlnsSdGetPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/GetPersonChangedAtDate/SD_GetPersonChangedAtDateInterface_20111201.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetPersonChangedAtDate {
            get {
                return ResourceManager.GetString("XmlnsSdGetPersonChangedAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:sd=&quot;http://rep.oio.dk/sd.dk/xml.schema/20080201/&quot; xsi:schemalocation=&quot;https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20111201/ https://service.sd.dk/sdws/xml/schema/sd.dk/xml.schema/20080201/SD_GetProfessionInterface.xsd&quot; .
        /// </summary>
        internal static string XmlnsSdGetProfession {
            get {
                return ResourceManager.GetString("XmlnsSdGetProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; .
        /// </summary>
        internal static string XmlnsW3 {
            get {
                return ResourceManager.GetString("XmlnsW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:xkom20050315=&quot;http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/&quot; .
        /// </summary>
        internal static string XmlnsXcom {
            get {
                return ResourceManager.GetString("XmlnsXcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;.
        /// </summary>
        internal static string XmlTag {
            get {
                return ResourceManager.GetString("XmlTag", resourceCulture);
            }
        }
    }
}
